# project_new/
#     app.py
#     config.py
#     extensions.py
#     models.py
#     rough.py
#     developer/
#         facemate.html
#         home.html
#         login.html
#         logout.html
#         register.html
#         register_student.html
#         register_teacher.html
#     modules/
#         student/
#             routes.py
#             __init__.py
#             templates/
#                 login_student.html
#                 student_dashboard.html
#             __pycache__/
#                 routes.cpython-313.pyc
#                 __init__.cpython-313.pyc
#         teacher/
#             routes.py
#             __init__.py
#             templates/
#                 login_teacher.html
#                 teacher_dashboard.html